# Useful commands to solve the exercises

### Length of a list 

In [1]:
# Length of a list: len(L)
L = [1, 2, 4, 4, 4, 5]
print('this list contains %i elements'% len(L))  

this list contains 6 elements


Use len() if you loop over the number of elements, your code does not have to be changed if you change the input list (size). 

### Command input()

In [3]:
# Command "input" to interactively enter a value 
time = input('What time is it?')
print('it is %s'% time)

What time is it? 16:10


it is 16:10


In [4]:
print(type(time))

<class 'str'>


### Conversion of/to int / float 

Such a conversion from one data type to another is also called casting

In [5]:
# int from a float
my_float = 34325. 
my_int = int(my_float)
my_second_float = float(my_int)
print(type(my_float), type(my_int), type(my_second_float))
print(my_float, my_int, my_second_float)

<class 'float'> <class 'int'> <class 'float'>
34325.0 34325 34325.0


### Rounding, floor and ceil

In [6]:
round(234.5), round(234.6)

(234, 235)

In [7]:
import numpy as np
print(np.floor(234.8))
print(np.ceil(234.8))

234.0
235.0


### String manipulation

In [8]:
'16:15'.split(sep=':')    # Split elements of a string based on a specific character
'16:15'.replace(':', ' ') # Replace a specific character in a string chain 
'16 15'.strip()           # remove white spaces from a string chain  

'16 15'

In [12]:
'16:15'.split(sep=':')

['16', '15']

### Reshape an array

In [14]:
a = np.array([1,2,3,5])
a_reshaped = a.reshape((2,2))
print(a_reshaped.shape)
print(a)
print(a_reshaped)

(2, 2)
[1 2 3 5]
[[1 2]
 [3 5]]


### Other useful numpy methods

#### Merging arrays

In [ ]:
np.append()  # Works like append for list
np.hstack()  # Horizontal stacking of 2 arrays
np.vstack()  # Vertical stacking of 2 arrays 
np.concatenate()   # Concatenate multiple arrays

In [ ]:
np.hstack()

#### Miscellanous

In [ ]:
np.sort()     # Sort elements of an array 
np.argsort()  # To get indices of the sorted elements


In [15]:
a = np.array([3,6,1,98,45])
np.sort(a)

array([ 1,  3,  6, 45, 98])

In [16]:
np.argsort(a)

array([2, 0, 1, 4, 3])

#### Statistics

In [ ]:
np.mean()    # mean of the elements of an array 
np.std()     # Standard deviation of the elements of an array 
np.median()  # Calculates the median of the elements of an array 

In [17]:
np.min(a)

1

In [18]:
np.argmin(a)

2