# Introduction to `numpy` -- Part 1 

This Notebook provides an overview of the capabilities of the `numpy` module. It covers Sect. II of [Modules_in_python_Overview.ipynb](02_01_Modules_in_python_Overview.ipynb). 

`numpy` implements fast array operations and mathematical functions for Python. This introduction is divided in 2 parts: Part 1 covers array creation and the object-oriented vocabulary you'll need; Part 2 covers what actually makes arrays *useful* (speed, indexing) and reading data from files.

## Table of Content

- [II.1 Array definition and construction](#II.1)
- [Intermezo: python is object-oriented](#intermezo)
- [II.1bis Data types (`dtype`)](#dtype)
- [Exercises](#exercises)
- [References](#refs)


## II.1 `array` definition and construction <a class="anchor" id="II.1"></a>

A `numpy` array is an object of type `np.ndarray`. There are several ways to build one:

``` python
import numpy as np
np.array([1, 2, 3, 4])              # from a python list
np.array([[0, 1, 2], [3, 4, 5]])    # 2D, from a nested list
np.empty(shape=(2, 3))              # uninitialized array, 2 rows x 3 columns
np.arange(5)                        # like the built-in range()
np.linspace(1, 10, 10)              # 10 evenly spaced elements from 1 to 10
np.zeros(10)                        # 10 elements, all 0
np.ones(10)                         # 10 elements, all 1
np.zeros((2, 5))                    # 2D, 2 rows x 5 columns
```

2D arrays of `shape=(r, c)` have `r` **rows** and `c` **columns**.


In [2]:
import numpy as np
a = np.array([[0, 1, 2], [3, 4, 5]])
a


array([[0, 1, 2],
       [3, 4, 5]])

In [4]:
type(a)

numpy.ndarray

In [6]:
a.dtype

dtype('int64')

In [3]:
a.shape

(2, 3)

In [7]:
my_empty_array = np.empty(shape=(2, 3))
my_empty_array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
zero_array = np.zeros(shape=(2, 3))
ones_array = np.ones(shape=(2, 2, 3))
print(zero_array)
print(ones_array.shape)   # note: 3 dimensions now


[[0. 0. 0.]
 [0. 0. 0.]]
(2, 2, 3)


In [13]:
print(np.arange(1., 5., 0.2))

[1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4 3.6 3.8 4.  4.2 4.4
 4.6 4.8]


In [14]:
print(np.arange(0., 5., 0.5))   # start, stop (excl.), step
print(np.linspace(0, 5, 9))     # start, stop (incl.), number of points


[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0.    0.625 1.25  1.875 2.5   3.125 3.75  4.375 5.   ]


`numpy` can also generate random arrays:
```python
np.random.random(size=4)   # uniform between 0 and 1
np.random.normal(size=4)   # standard-normal distributed
```
and compute common math functions elementwise: `np.log10()`, `np.log()`, `np.exp()`, `np.sin()`, `np.cos()`, etc. (full list [here](https://docs.scipy.org/doc/numpy/reference/routines.math.html)).


In [16]:
# try a couple of the commands above
print(np.random.random(size=4))
print(np.log(2.3))    # Natural log
print(np.log10(2.3))  # Base 10

[0.30823522 0.70344993 0.35361618 0.2781017 ]
0.8329091229351039
0.36172783601759284


## Intermezo: python is an object-oriented language <a class="anchor" id="intermezo"></a>

Creating a variable of a given type generally means creating an **object**. You don't need deep OOP knowledge for this course, but three words will come up constantly:

- **instance**: `a = np.array([[1, 2, 3], [3, 5, 5]])` creates an *instance* of the array object (in practice: allocates memory for it).
- **attribute**: a property attached to an instance, e.g. `a.shape`. Access it with `instance.attribute` (no parentheses).
- **method**: a function attached to an instance that can act on it, e.g. `a.mean()`. Access it with `instance.method(args)` (parentheses, even with no arguments).

Most attributes/methods also have an equivalent standalone function: `a.shape` &harr; `np.shape(a)`, and `a.mean()` &harr; `np.mean(a)`.


In [17]:
print(a.shape)        # attribute -- no parentheses
print(np.shape(a))     # equivalent standalone function
print(a.mean())        # method -- parentheses, even with no arguments


(2, 3)
(2, 3)
2.5


## II.1bis Data types (`dtype`) <a class="anchor" id="dtype"></a>

Every array has a `dtype`: the type of the elements it contains (as opposed to `type(a)`, which just tells you `a` is a `numpy.ndarray`). The default is floating point; you can also request `int`, `complex`, `bool`, or string types explicitly.

```python
c = np.array([1, 2, 3], dtype=float)       # dtype('float64')
d = np.array([1+2j, 3+4j, 5+6j])           # dtype('complex128')
e = np.array([True, False, True])          # dtype('bool')
f = np.array(['abc', 'eddafg', 'hjk'])     # dtype('<U6') -- strings, max length 6
```

**Important:** only *arrays* have a `.dtype`. A plain python `list` doesn't (`L.dtype` raises an `AttributeError`) — `type()` works on both, `.dtype` is array-only.


**Quick exercise.** Create, in a single cell: a float array, a boolean array, and a string array (pick your own small values). Print each one's `.dtype`. Then create a plain python list with the same values as one of your arrays, and try `.dtype` on it — confirm you get an `AttributeError`. 


In [21]:
f = np.array(['abc', 'eddafg', 'hjk'])
print(f.dtype)
f[2] = '12345678'  # BEWARE !!  
print(f.dtype)
# The type has not changed but the string got silently truncated by python 

<U6
<U6


In [20]:
print(f)

['abc' 'eddafg' '123456']


In [22]:
# Quick exercise: dtype tour
float_list = [1., 2., 58845., 2.]
string_list = ['abc', 'eddafg', 'hjk']
bool_list = [True, False, True]
float_array = np.array(float_list)
string_array = np.array(string_list)
bool_array = np.array(bool_list)
print(float_array.dtype)
print(string_array.dtype)
print(bool_array.dtype)



float64
<U6
bool


In [23]:
# If I try with the list
print(float_list.dtype)

AttributeError: 'list' object has no attribute 'dtype'

In [24]:
# But list elements have a type 
for elt in float_list:
    print(type(elt))

<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>


In [26]:
print(type(float_list))

<class 'list'>


## Exercises <a class="anchor" id="exercises"></a>

**Exercise 1 — shape & dimensions.** For the array

```python
a = np.array([[1, 2, 3, 4], [4, 5, 6, 7], [2, 3, 4, 5]])
```

- What do `a.ndim`, `a.shape`, and `len(a)` each give you? How does each relate to rows/columns/dimensions?
- How do you access the 2nd item of the first row?
- Try the same three questions on `b = np.array([[1, 2, 3], []])` — what's different, and why?


In [29]:
# (1) shape & dimensions
a = np.array([[1, 2, 3, 4], [4, 5, 6, 7], [2, 3, 4, 5]])
print(a)
print(a.ndim)   # Gives you the dimension of the array 
print(a.shape)  # Gives the precise shape 
print(len(a))   # Gives the number of rows (first dimension)
# Access 2nd item of first row
print(a[0, 1])  # first row -> 0 ; 2nd item -> 1 

[[1 2 3 4]
 [4 5 6 7]
 [2 3 4 5]]
2
(3, 4)
3
2


In [39]:
# (1, continued) b = np.array([[1, 2, 3], []])
b = np.array([[1, 2, 3], []])
print(b)
# This does not work because we incorrectly instanciated the array 

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

**Exercise 2 — elementwise operations, two ways.** 

Take `a = np.arange(10)`. Add the even-indexed elements to the odd-indexed elements (i.e. `a[0]+a[1]`, `a[2]+a[3]`, ...) using **two** different techniques: (a) slicing, (b) a list comprehension. Then use `%timeit` to compare their speed.


In [34]:
# (2) elementwise addition: slicing vs. list comprehension, timed
a = np.arange(10)
b = a[0::2] + a[1::2]
print(a[0::2]) 
print('+')
print(a[1::2])
print('=')
print(b)

[0 2 4 6 8]
+
[1 3 5 7 9]
=
[ 1  5  9 13 17]


In [43]:
# Now what about list comprension: 
a = np.arange(10)
c = [a[i] + a[i+1] for i in range(0, 10, 2)]
c

[np.int64(1), np.int64(5), np.int64(9), np.int64(13), np.int64(17)]

In [44]:
%timeit b = a[0::2] + a[1::2]

403 ns ± 3.84 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [45]:
%timeit [a[i] + a[i+1] for i in range(0, 10, 2)]

642 ns ± 3.06 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


**Exercise 3 — build two arrays.** Generate two arrays with 5 elements such that:
- the first one is `[2^0, 2^1, 2^2, 2^3, 2^4]`
- the second one follows `a_i = 2^(3i) - i`

Expected output:
```python
[1 2 4 8 16]
[  1   7  62 509 4092]
```
*(Hint: build them from `np.arange(5)` using vectorized operators — no loop needed.)*


In [35]:
# (3) two arrays from a formula

powers = np.arange(5)
Two_to_powers = 2**powers
print(Two_to_powers)


[ 1  2  4  8 16]


In [37]:
# a_i = 2^(3i) - i
ii = np.arange(5)
a = 2**(3 * ii) - ii 
a 

array([   1,    7,   62,  509, 4092])

It is now time for more practicing exercises: GO TO [Python_Exercises_starter.ipynb](../Exercises/Python_Exercises_starter.ipynb)

To take full advantage of numpy arrays, you need to understand in more detail how they work under the hood — let's move to [Part 2](02_03_Modules_in_python_numpy_Part2.ipynb): copies vs. views, reshaping, `ufunc`s, aggregation, broadcasting, and indexing.


## References and supplementary material <a class="anchor" id="refs"></a>

- Good video introducing numpy (and that inspired part of this notebook) by J. Vanderplas: https://www.youtube.com/watch?v=EEUXKG97YRw
- Numpy quick-start: https://numpy.org/doc/stable/user/quickstart.html
