# Introduction to `numpy` - Part 1

This Notebook provides an overview of the capabilities of the `numpy` module. It covers Sect. II of [Modules_in__python.ipynb](Modules_in__python.ipynb). 

## Table of Content

- [II. Numpy](#II)
    * [II.1 Array Definition and construction](#II.1)
    * [II.2 Array copies and views](Modules_in__python_numpy_Part2.ipynb/#II.2)
    * [II.3 Shape manipulation](Modules_in__python_numpy_Part2.ipynb/#II.3)
    * [II.4 What makes numpy Arrays useful structures ?](Modules_in__python_numpy_Part2.ipynb/#II.4)
        - II.4.1 ufunc
        - II.4.2 Aggregation
        - II.4.3 Broadcasting
        - II.4.4 Slicing, masking, fancy indexing
    * [II.5 Reading arrays from a file and string formatting](Modules_in__python_numpy_Part2.ipynb/#II.5)
    * [II.6 Useful Numpy functions](Modules_in__python_numpy_Part2.ipynb/#II.6)
    * [II.7 Summary](Modules_in__python_numpy_Part2.ipynb/#II.7)
    * [II.8 References](#VI)

## II. `numpy`:  <a class="anchor" id="II"></a>

`numpy` can be seen as the implementation of mathematical functions and operations for python language. It also introduces one key object `arrays`. 

### II.1 `array` definition and construction:  <a class="anchor" id="II.1"></a>

- A `numpy` array is an object of the type `np.ndarray` (although this type specifier is rarely used directly). Instead one can create arrays in several ways: 

``` python
import numpy as np
np.array([1,2,3,4])   # creates an array from a python list
np.array([[0, 1, 2], [3, 4, 5]])   # Creates a 2D array from a python list
np.empty(shape=(2,3)) # Creates an "empty" (entry not initialised) array with 2 rows and 3 columns 
np.arange(5) # similar to the built-in range() function.
np.linspace(1, 10, 10) # creates an array of 10 elements from 1 to 10
np.zeros(10)  # creates an array of 10 elements filled with 0
np.ones(10)   # creates an array of 5 elements filled with 1
np.zeros((2, 5))  # multidimensional arrays of 2 rows and 5 columns

```
- 2-D arrays of `shape=(r, c)` are arrays with `r` *rows* and `c` *columns*. 

In [1]:
# Let's try the above commands and visualise the output. 
import numpy as np
a = np.array([1,22,3])
a

array([ 1, 22,  3])

In [2]:
type(a)

numpy.ndarray

In [3]:
a.dtype

dtype('int64')

In [4]:
# Now we create an array of floats
a_of_floats = np.array([1.,22.,3.])
a_of_floats.dtype

dtype('float64')

In [5]:
# Access elements using slicing 
a[0:2]

array([ 1, 22])

In [6]:
# operation elementwise for arrays 
print('a=', a)
b = a + a 
print('b=', b)

a= [ 1 22  3]
b= [ 2 44  6]


In [7]:
c = a + b 
print('a=', a)
print('b=', b)
print('c=', c)

a= [ 1 22  3]
b= [ 2 44  6]
c= [ 3 66  9]


In [8]:
# Now 2D arrays 
a_2d = np.array([[1, 22, 3], [4, 5, 6]])
a_2d

array([[ 1, 22,  3],
       [ 4,  5,  6]])

In [9]:
a_2d + a_2d

array([[ 2, 44,  6],
       [ 8, 10, 12]])

In [10]:
c_2d = 3 * a 
print(c_2d)

[ 3 66  9]


In [11]:
a_2d

array([[ 1, 22,  3],
       [ 4,  5,  6]])

In [12]:
# access first row 
a_2d[0, :]

array([ 1, 22,  3])

In [13]:
# Access 2nd column, all row
a_2d[:, 1]

array([22,  5])

In [14]:
c_2d[0, ]

3

In [15]:
a_of_s = np.array(['s','a','d'])
a_of_s

array(['s', 'a', 'd'], dtype='<U1')

In [16]:
a_2d.shape

(2, 3)

In [17]:
empty_w_2rows_3colums = np.empty((2, 3))
print(empty_w_2rows_3colums)

[[0. 0. 0.]
 [0. 0. 0.]]


In [18]:
ones_w_2rows_3colums = np.ones((2, 3), dtype=bool)
print(ones_w_2rows_3colums )

[[ True  True  True]
 [ True  True  True]]


In [19]:
print(ones_w_2rows_3colums.dtype)

bool


In [20]:
zeros_alike_a_2d = np.zeros_like(a_2d)
print(zeros_alike_a_2d)

[[0 0 0]
 [0 0 0]]


### Intermezo: python is an object-oriented language

At this stage, it is important to make one thing clear: in python, creating a variable of a given type generally corresponds to creating an object. You do not have to have a deep understanding of object-oriented programing (OOP) to work in python (at least at an introduction level - in this course) but there are a few concepts that may be helpful to know. We will illustrate the jargon by taking the example of the object `array` in numpy, but the concepts illustrated herebelow are *not* specific to numpy. 

- The object that `numpy` works with is called an `array`. 
- Once you assign an array to a variable, such as  
```python   
a = np.array([[1,2,3], [3,5,5]])
```
you create an **instance** of an array object (in practice you mostly allocate memory). Note that you can work with arrays created on the fly without saving them as a variable. You can see this as a dummy instantiation.  
- An object has **attributes**. As a chair can be in wood, plastic, metal, ... objects have attributes. For example, the `shape` is an attribute of an array. This is a property which is attributed to the instance of the object. You can access an object attribute using `instance.attribute`, i.e. to know the shape of `a` you can do: 
```python
a.shape
```
You can however also get to know the shape of `a` by writing `module.attribute(instance)`: 
```python
np.shape(a) 
``` 
- Some functions can do operations on the object and return something. Such functions defined in an object class are formally called **methods**. Again, you can call a method by using the `.` directly on the instance `instance.method(args)` (note the subtle difference with attributes: there are parentheses in the call regardless of whether arguments are provided or not): 
```python
a.cumsum(axis=1)
a.mean()
```
Alternatively you can call the corresponding function by doing `module.function(a, args)`, providing the array instance as the first argument:
```python
np.cumsum(a, axis=1)
np.mean(a)
```

In [21]:
a.shape   # The shape is an attribute of an array 

(3,)

In [22]:
# you can also find the shape of an array by seeking the shape of an array with the command np.shape()
np.shape(a)        # this is equivalent 

(3,)

In [23]:
empty_array = np.empty(shape=(2,3))
empty_array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
zero_array = np.zeros(shape=(2,3))
zero_array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
ones_array = np.ones(shape=(2,2,3))
ones_array  # [1,1,0]

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [26]:
type(zero_array)

numpy.ndarray

In [27]:
zero_array.dtype

dtype('float64')

In [28]:
array_of_string = np.array(['qqqq', 'a', 'f'], dtype=str)
array_of_string

array(['qqqq', 'a', 'f'], dtype='<U4')

In [29]:
for i in range(5):
    print(i)

0
1
2
3
4


In [30]:
np.arange(0., 5., 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [31]:
np.linspace(0, 5, 9)

array([0.   , 0.625, 1.25 , 1.875, 2.5  , 3.125, 3.75 , 4.375, 5.   ])

- numpy has also tools to create arrays filled with random elements:

``` python
np.random.random(size=4)  # uniform between 0 and 1
np.random.normal(size=4)  # elements are std-normal distributed

```

In [32]:
# Try out the above commands
np.random.random(5)

array([0.92336494, 0.41398827, 0.61690043, 0.76174559, 0.90570253])

- You can explicitly specify which **data-type** you want:

``` python 
c = np.array([1, 2, 3], dtype=float)
c.dtype
    Out: dtype('float64')
```

In [33]:
# Try out the above commands 
c = np.array([1, 2, 3], dtype=float)
c.dtype

dtype('float64')

The default data type is floating point. Other possible data types are: 

* **COMPLEX** numbers: 
``` python
d = np.array([1+2j, 3+4j, 5+6*1j])
d.dtype
    Out: dtype('complex128')
```

In [35]:
# Try out the above commands 
d = np.array([1+2j, 3, 5+6*1j])  # Implicit conversion of 3 into a complex
print(d, d.dtype)

[1.+2.j 3.+0.j 5.+6.j] complex128


* **BOOL**:
``` python
e = np.array([True, False, False, True])
e.dtype
    Out: dtype('bool')
```

In [36]:
# Try out the above commands 
e = np.array([True, False, False, True])
e.dtype

dtype('bool')

* **String**:
``` python
f = np.array(['abc', 'eddafg', 'hjk'])
f.dtype
    Out: dtype('S6')   # <--- String of 6 characters (by default largest elements of the array 
```

In [37]:
# Try out the above commands 
f = np.array(['abc', 'eddafg', 'hjk'])
f.dtype

dtype('<U6')

* **Other data types**:  `int32`, `int64`, `uint32`, `uint64`  (uint = unsigned integer => only positive integers)

Note that `type(f)` tells you that `f` is a numpy array, while `f.dtype` gives you the *type of the elements* containted in `f`. `dtype` is an attribute of the object `np.array`. If you try to access the attribute dtype of a List, you will get an error message. 

In [38]:
# Difference between type/dtype; application to List/arrays.
f = np.array(['abc', 'eddafg', 'hjk'])
print(type(f))
print(f.dtype)
print('----------')
L = ['abc', 'eddafg', 'hjk']
print(type(L))
print(L.dtype)

<class 'numpy.ndarray'>
<U6
----------
<class 'list'>


AttributeError: 'list' object has no attribute 'dtype'

- Last but not least, `numpy` is also the package that allows you to calculate many common mathematical function (see also [`ufunc`](#II.4.1)): `np.log10()` (base 10 log), `np.log()` (natural log), `np.exp()`, `np.sin()`, `np.cos()`, etc. See the list of `numpy` mathematical functions [here](https://docs.scipy.org/doc/numpy/reference/routines.math.html)

In [39]:
# create an array of floats and calculate its log / sin / ... 
#x = np.linspace(-2*np.pi, 2*np.pi, 20.)
np.log(2.3)

0.8329091229351039

In [40]:
np.log(a)

array([0.        , 3.09104245, 1.09861229])

In [41]:
# Illustration of the strength of arrays compared to list
an_array = np.array([0.1, 0.8, 3., 0.6])
print(np.log(an_array))
a_list = [0.1, 0.8, 3., 0.6]
for i in range(4):
    print(np.log(a_list[i]))

[-2.30258509 -0.22314355  1.09861229 -0.51082562]
-2.3025850929940455
-0.2231435513142097
1.0986122886681098
-0.5108256237659907


**Exercise:**   
For the array:
``` python
a = np.array([[1,2,3,4], [4,5,6,7], [2,3,4,5] ])
```
- What is the output of `a.ndim`, `a.shape`, `len(a)` ?     
- How does the above commands relate to the rows, columns, dimensions ?       
- How do you access 2nd item of the first row ?   

*Note:* 
Try to do the same with the following array:
``` python
b = np.array([[1,2,3], []])
```

In [42]:
a = np.array([[1,2,3,4],
              [4,5,6,7],
              [2,3,4,5]])
print(a.ndim)
print(a.shape)

2
(3, 4)


In [43]:
len(a)

3

> `ndim` provides the number of axis of an array, `shape` the length of each axis, and len() the length of the first axis (axis 0 <-> number of rows). 

**Exercises:** Elementwise operations

In the code cell below, try simple arithmetic elementwise operations: 
- add even elements with odd elements using 2 different techniques (slicing and list comprehension)
- Time the two solution using %timeit.

In [44]:
# basic solution with numpy (involves 2 arrays)
a = np.arange(0,10,2)
b = np.arange(1,11,2)
a+b

array([ 1,  5,  9, 13, 17])

In [45]:
# more elegant solution with numpy (involves 1 array)
a = np.arange(0,10,1)
a[0::2]+a[1::2]

array([ 1,  5,  9, 13, 17])

In [46]:
%timeit a[0::2]+a[1::2]

981 ns ± 13.8 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [47]:
%timeit np.arange(0,10,2)+np.arange(1,11,2)

2.28 µs ± 7.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [48]:
# solution with list comprehension
c = [i+i+1 for i in range(0,10,2)]
c

[1, 5, 9, 13, 17]

In [49]:
%timeit [i+i+1 for i in range(0,10,2)]

875 ns ± 4.51 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


> One can notice that for 10 elements, the list comprehension solution is 50\% faster than the solution involving the instanciation of one numpy array, which is itself ~twice faster than the solution involving two numpy arrays. This is most likely due to the process of creating instance of numpy array objects.

Let's now try the same as above but with 1000 elements:

In [50]:
%timeit np.arange(0,1000,2)+np.arange(1,1001,2)

3.56 µs ± 52.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [51]:
%timeit [i+i+1 for i in range(0,1000,2)]

55.8 µs ± 1.14 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


> We can notice that the numpy solution is now over 10x faster. The numpy solution is in fact barely longer than in the case of 10 elements. The main reason the list solution gets slower is that for each element of the list that is created, python has to check the types involved (and if any operation, like a sum here, is allowed between these types). This is not the case with numpy arrays - as their type is defined with dtype, and only a single check is enough to know whether the operation between the two arrays (here a sum) is allowed.

- Generate 2 arrays such that their elements are as follow :    
   `[2^0, 2^1, 2^2, 2^3, 2^4]`    
   `a_i = 2^(3*i) - i `    
   
Expected output: 
``` python
[1 2 4 8 16]    
[  1   7  62 509]    
```

In [52]:
a = np.arange(5)
2**a

array([ 1,  2,  4,  8, 16])

In [53]:
a = np.arange(4)
a = 2**(3*a) - a # note that we override the first definition of 'a' above. Python is dynamical.
a

array([  1,   7,  62, 509])

It is now time for more practicing exercises: GO TO [Python_Exercises_starter.ipynb](../Exercises/Python_Exercises_starter.ipynb)

To take full advantage of numpy arrays, you need to understand in more details how they work. For this let's go to the second part of this notebook: [Modules_in__python_numpy_Part2.ipynb](Modules_in__python_numpy_Part2.ipynb)

## II.8 References and supplementary material: <a class="anchor" id="VI"></a>

- Good video introducing numpy (and that inspired part of the numpy section of this notebook) by J. Vandeplas: https://www.youtube.com/watch?v=EEUXKG97YRw

- Numpy quick-start:  [https://numpy.org/doc/stable/user/quickstart.html](https://numpy.org/doc/stable/user/quickstart.html)

- About string formatting: https://docs.python.org/3/tutorial/inputoutput.html